# Generated by Django 3.1.5 on 2021-01-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reimburse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('document_attach', models.FileField(upload_to='static/docs')),
                ('document_type', models.CharField(choices=[('PDF', 'document/pdf'), ('JPG', 'image/jpg'), ('PNG', 'image/png')], default='JPG', max_length=3)),
                ('description', models.TextField()),
            ],
        ),
    ]
