# Generated by Django 3.1.5 on 2021-01-12 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimburse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('document_attach', models.FileField(upload_to='upload')),
                ('document_type', models.CharField(choices=[('PDF', 'document/pdf'), ('JPG', 'image/jpg'), ('PNG', 'image/png')], default='JPG', max_length=3)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('food_and_beverage', 'Food and beverage'), ('office_supplies', 'Office supplies'), ('other', 'other')], default='transport', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('on_progress', 'on_progress'), ('completed', 'completed'), ('rejected', 'rejected')], default='submitted', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=25, max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
