# Generated by Django 3.1.5 on 2021-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimburse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimburse',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reimburse',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
